#!/usr/bin/env bash


prefix="package_rest_kafka_connect_$2"

if [[ "package_rest_kafka_connect_rest_kafka_connect_rest_elasticsearch_data_volume" == "$prefix"* ]] ; then
	executionplane --silent docker volume create package_rest_kafka_connect_rest_kafka_connect_rest_elasticsearch_data_volume
	fi
	
